name = "mcp-filesystem"
main = "fastmcp-wrapper/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
# Build the original TypeScript server first
command = "npm install && npm run build"

[vars]
MCP_VERSION = "2024-11-05"

# R2 bucket binding for file storage
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "mcp-user-storage"

# KV namespace for metadata and quotas
[[kv_namespaces]]
binding = "STORAGE_METADATA"
id = "9a69f660b8d44461ac887eccc27b1070"

# The dispatch namespace for Workers for Platforms
[[dispatch_namespace]]
binding = "MCP_DISPATCH"
namespace = "mcp-servers"

# Secrets to configure (set with wrangler secret put):
# JWT_SECRET - For JWT token validation