version: '3.8'

services:
  trello-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MCP_SERVER_PORT:-8000}:${MCP_SERVER_PORT:-8000}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - USE_CLAUDE_APP=false  # Use SSE mode by default in Docker
    restart: unless-stopped 