name = "mcp-memory"
main = "fastmcp-wrapper/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
# Build the original TypeScript server first
command = "npm install && npm run build"

[vars]
MCP_VERSION = "2024-11-05"

# KV namespace for memory storage
[[kv_namespaces]]
binding = "MEMORY_KV"
id = "memory-namespace-id"

# The dispatch namespace for Workers for Platforms
[[dispatch_namespace]]
binding = "MCP_DISPATCH"
namespace = "mcp-servers"

# Secrets to configure (set with wrangler secret put):
# JWT_SECRET - For JWT token validation